DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS addresses CASCADE;

DROP TABLE IF EXISTS orders CASCADE;

DROP TABLE IF EXISTS order_lines CASCADE;

DROP TABLE IF EXISTS products;



CREATE TABLE IF NOT EXISTS users
(
    user_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name   varchar(50) NOT NULL,
    last_name    varchar(50) NOT NULL,
    email        varchar(50) NOT NULL UNIQUE,
    phone_number varchar(10) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS addresses
(
    address_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT REFERENCES users (user_id) NOT NULL,
    country      varchar(50)                       NOT NULL,
    city         varchar(50)                       NOT NULL,
    street       varchar(50)                       NOT NULL,
    house_number varchar(50)                       NOT NULL,
    flat_number varchar(50)
);

CREATE TABLE IF NOT EXISTS orders
(
    order_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT REFERENCES users (user_id) NOT NULL,
    creation_date TIMESTAMP WITHOUT TIME ZONE,
    delivery_date TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS products
(
    product_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(255) NOT NULL,
    description text         NOT NULL,
    price       numeric      NOT NULL
);

CREATE TABLE IF NOT EXISTS order_lines
(
    order_line_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      BIGINT REFERENCES orders (order_id)     NOT NULL,
    product_id    BIGINT REFERENCES products (product_id) NOT NULL,
    quantity      NUMERIC                                 NOT NULL,
    measure_unit  varchar(50)                             NOT NULL CHECK (measure_unit IN ('KG', 'G', 'MG', 'M', 'SM', 'MM', 'PCS'))
);